# Generated by Django 4.0.1 on 2022-01-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=22, verbose_name='CNPJ')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Ração', 'Ração'), ('Remédio', 'Remédio'), ('Ferramenta', 'Ferramenta'), ('Outro', 'Outro')], default='-----', max_length=15, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
