# Generated by Django 4.0.1 on 2022-01-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_fornecedor_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='temVarejo',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('-----', '-----'), ('Ração', 'Ração'), ('Remédio', 'Remédio'), ('Ferramenta', 'Ferramenta'), ('Outro', 'Outro')], default='-----', max_length=15, verbose_name='Tipo'),
        ),
    ]
